### ISSUE TITLE
Поправить название переменной в lw1/task1.hs

### ISSUE THREAD

**Issue by qasmark** [daug32/Volgatech.FunctionalAndLogicProgramming#1]
```Haskell
-- task1.hs
array = ( ( 1, 'a' ), "abc" )
main = print( snd ( fst ( array ) ) )
```

Лучше переименовать **array** на **tuple** , поскольку array  в Haskell обозначается через [], а () задается кортеж 

В остальном все супер, 12/12, красавчик

**Comment by daug32** [comment]
won't do
